apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: k8tz
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: k8tz

  source:
    repoURL: https://k8tz.github.io/k8tz/
    chart: k8tz
    targetRevision: 0.9.0

    helm:
      values: |
        namespace: k8tz
        timezone: Asia/Kolkata
        replicaCount: 1

        webhook:
          ignoredNamespaces:
            - kube-system
            - minside